### ISSUE TITLE
Github Actions produces gmp_mod(): Argument #1 ($num1) must be of type GMP|string|int error

### ISSUE THREAD

**Issue by sts-ryan-holton** [vinkla/hashids#200]
When running my Laravel test suite via Github Actions I get the following error:

> gmp_mod(): Argument #1 ($num1) must be of type GMP|string|int, Illuminate\Support\Stringable given

![Screenshot 2024-04-11 at 15 31 17](https://github.com/vinkla/hashids/assets/25177538/94b858c6-7ee5-44bc-b260-3511caed27c2)

Also see my workflow file:

```yml
name: tests

on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true
      matrix:
        php: [8.3]
        laravel: [11]
        exclude:
          - php: 8.3
            laravel: 11

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, bcmath
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress

      - name: Create SQLite database file
        run: |
          if [ ! -f database/database.sqlite ]; then
            touch database/database.sqlite
          fi

      - name: Run migrations
        run: php artisan migrate
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite

      - name: Execute tests
        run: vendor/bin/phpunit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
```

What am I missing? My test calls Hashids like: `(new Hashids('', 7))->encode(rand(11111111, 99999999).''.rand(111111, 999999))`
